In [1]:
import pandas as pd

In [2]:
schema = pd.read_csv("C:/Users/Администратор/Desktop/DA33_HOMEWORK/PROJECT_Python/survey_results_schema.csv")
data = pd.read_csv("C:/Users/Администратор/Desktop/DA33_HOMEWORK/PROJECT_Python/survey_results_public.csv")

C:\Users\Администратор\AppData\Local\Temp\ipykernel_8032\2241525513.py:2: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("C:/Users/Администратор/Desktop/DA33_HOMEWORK/PROJECT_Python/survey_results_public.csv")

In [3]:
schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [4]:
data

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1. Підрахунок загальної кількості респондентів

In [5]:
total_respondents = data['ResponseId'].nunique()
print(f"Total respondents: {total_respondents}")

Total respondents: 49191

## 2. Аналіз повноти відповідей респондентів

In [6]:
schema_questions = set (schema['qname'])
data_columns = set (data.columns)
questions = list(schema_questions & data_columns)

all_answers = data.dropna(subset=questions)

print(f"Number of questions: {len(questions)}")
print(f"Respondents with all answers: {len(all_answers)}")

Number of questions: 126
Respondents with all answers: 0

## 3. Статистичний аналіз досвіду респондентів

In [7]:
# Пропущені значення були виключені з аналізу, оскільки mean(), median(), mode() у Pandas за замовчуванням ігнорують NaN

mean_exp = data['WorkExp'].mean()
median_exp = data['WorkExp'].median()
mode_exp = data['WorkExp'].mode()[0]

stats_table = pd.DataFrame({
    'Metric': ['Mean', 'Median', 'Mode'], 
    'WorkExp': [round(mean_exp, 2), median_exp, mode_exp]})

print("Work Experience statistics:")
print(stats_table)

Work Experience statistics:
   Metric  WorkExp
0    Mean    13.37
1  Median    10.00
2    Mode    10.00

## 4. Аналіз віддаленої роботи

In [8]:
[col for col in data.columns 
 if 'remote' in col.lower()]

['RemoteWork']

In [9]:
data['RemoteWork'].value_counts(dropna=False)

RemoteWork
NaN                                                                             15411
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [10]:
remote_workers = data[data['RemoteWork'] == 'Remote']

print(f"Remote workers: {len(remote_workers)}")

Remote workers: 10931

## 5. Визначення популярності Python

In [11]:
[col for col in data.columns 
 if 'language' in col.lower()]

['LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry']

In [12]:
data['LanguageHaveWorkedWith'].value_counts(dropna=False)

LanguageHaveWorkedWith
NaN                                                                  17520
HTML/CSS;JavaScript;TypeScript                                         370
Python                                                                 229
C#;HTML/CSS;JavaScript;SQL;TypeScript                                  193
HTML/CSS;JavaScript;PHP;SQL                                            180
                                                                     ...
Bash/Shell (all shells);COBOL;HTML/CSS;JavaScript;Python;SQL;VBA         1
C++;Dart;GDScript;HTML/CSS;JavaScript;PHP;PowerShell;Python;R;SQL        1
Ada;Assembly;Erlang;F#;Fortran;GDScript;Go;Groovy                        1
C;Go;HTML/CSS;JavaScript;MATLAB;MicroPython;Python;Rust                  1
Dart;HTML/CSS;JavaScript;Kotlin;PHP;Python;Rust;Swift;TypeScript         1
Name: count, Length: 15479, dtype: int64

In [17]:
# розрахунок відсотка популярності Python від респондентів, які відповіли на питання про мови програмування (не від всіх респондентів)
python_users = data['LanguageHaveWorkedWith'].str.contains('Python', na=False).sum()

total_respondents = data['LanguageHaveWorkedWith'].notna().sum()

python_percent = python_users / total_respondents * 100

print(f"Python users: {python_users}")
print(f"Percentage of Python users:  {python_percent:.1f}%")

Python users: 18466
Percentage of Python users:  58.3%

## 6. Аналіз шляхів навчання програмуванню

In [14]:
[col for col in data.columns 
 if 'learn' in col.lower()]

['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow']

In [15]:
online_leaners = data['LearnCode'].str.lower().str.contains('online courses', na=False).sum()

print(f" Responders who learned via online courses: {online_leaners}")

 Responders who learned via online courses: 10973

## 7. Географічний аналіз компенсації Python-розробників

In [16]:
[col for col in data.columns
if 'country' in col.lower()]

['Country']

In [17]:
python_dev = data[data['LanguageHaveWorkedWith'].str.contains('Python', na=False)].copy()

python_dev['ConvertedCompYearly'] = pd.to_numeric(python_dev['ConvertedCompYearly'], errors='coerce')

python_dev_clean = python_dev.dropna(subset = ['ConvertedCompYearly'])

comp_by_country = (python_dev_clean.groupby('Country')['ConvertedCompYearly']
                  .agg(mean_compensation='mean', median_compensation='median'))

comp_by_country['mean_compensation'] = comp_by_country['mean_compensation'].round(0)

comp_by_country

                                      mean_compensation  median_compensation
Country
Afghanistan                                     22329.0               1000.0
Albania                                         47218.0              50000.0
Algeria                                         20187.0               7088.0
Andorra                                        226104.0             226103.5
Antigua and Barbuda                                 1.0                  1.0
...                                                 ...                  ...
Venezuela, Bolivarian Republic of...             9909.0               3000.0
Viet Nam                                       218837.0               8254.0
Yemen                                           32930.0              23672.0
Zambia                                           5424.0               3206.0
Zimbabwe                                        34000.0              25500.0

[153 rows x 2 columns]

In [18]:
comp_by_country.sort_values(by='mean_compensation', ascending=False).head(15)

,mean_compensation,median_compensation
Country,,
Oman,390135.0,390135.0
Andorra,226104.0,226103.5
Viet Nam,218837.0,8254.0
United States of America,173299.0,150000.0
Switzerland,156457.0,142592.0
Singapore,147515.0,91391.0
Israel,135828.0,142594.0
Nigeria,128773.0,1808.0
Ireland,120524.0,116015.0
Nomadic,120132.0,139218.0
Australia,118091.0,97514.0
United Kingdom of Great Britain and Northern Ireland,117662.0,94958.5
Luxembourg,116015.0,109054.0
Denmark,115672.0,98289.0
Lebanon,115540.0,65000.0

## 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [19]:
top_5 = data.sort_values(by='ConvertedCompYearly', ascending=False).head(5)

top_5[['EdLevel', 'ConvertedCompYearly']]

                                               EdLevel  ConvertedCompYearly
34267              Associate degree (A.A., A.S., etc.)           50000000.0
28700  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           33552715.0
43143              Associate degree (A.A., A.S., etc.)           18387548.0
35353     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           15430267.0
45971  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           13921760.0

## 9. Аналіз популярності Python по віковим категоріям

In [20]:
python_dev_by_age = (python_dev.groupby('Age')['Age'].agg('count'))
dev_by_age = (data.groupby('Age')['Age'].agg('count'))

In [21]:
age_stats = pd.DataFrame({'python_count': python_dev_by_age, 'total_count': dev_by_age})

age_stats['python_%'] = (age_stats['python_count'] / age_stats['total_count'] * 100).round(1)

age_stats

                   python_count  total_count  python_%
Age
18-24 years old            3684         9210      40.0
25-34 years old            6102        16519      36.9
35-44 years old            4862        13241      36.7
45-54 years old            2424         6275      38.6
55-64 years old             978         2626      37.2
65 years or older           298          942      31.6
Prefer not to say           118          378      31.2

## 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [22]:
[col for col in data.columns
if 'industry' in col.lower()]

['Industry']

In [23]:
quant_75 = data['ConvertedCompYearly'].quantile(0.75)

high_paid_remote = data[(data['RemoteWork'] == 'Remote') & (data['ConvertedCompYearly'] > quant_75)
]
high_paid_remote.shape[0]

2461

In [24]:
industry_counts = high_paid_remote['Industry'].value_counts()
industry_counts.head(15)

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64